version: '3.8'
services:  
  ##########################################################################     
  # MySQL 
  mysql:
    container_name: mysql
    image: mysql:5.7     
    volumes:
      - ./mysql-volume:/var/lib/mysql   
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cuentabancaria
      MYSQL_ROOT_PASSWORD: pruebadevsu 

  ##########################################################################     
  # Microservicio1      
  microservicio1:
    container_name: microservicio1
    build:
      context: PruebaMicroServicio1
      dockerfile: Dockerfile
    image: prueba_microservicio_1
    ports:
      - "8081:8081"
    environment:
      - server.port=8081
      - spring.datasource.url=jdbc:mysql://mysql:3306/cuentabancaria 
      - spring.datasource.username=root
      - spring.datasource.password=pruebadevsu
    depends_on:
      - mysql

  ##########################################################################     
  # Microservicio2     
  microservicio2:
    container_name: microservicio2
    build:
      context: PruebaMicroServicio2
      dockerfile: Dockerfile
    image: prueba_microservicio_2
    ports:
      - "8082:8082"
    environment:
      - server.port=8082
      - spring.datasource.url=jdbc:mysql://mysql:3306/cuentabancaria
      - spring.datasource.username=root
      - spring.datasource.password=pruebadevsu
      - cliente.service.url=http://microservicio1:8081/clientes/ 
    depends_on:
      - mysql
      - microservicio1